AG-51049 Add stricter ESLint rules for class members, JSDoc style, and FIXME comments
Squashed commit of the following:

commit abcf2ba5d4ebaf94659214a0f0a87f1bf5dfc99c
Merge: f0575d22d 188d2c1c7
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Fri Apr 10 13:22:05 2026 +0300

    Merge branch 'release/v2.10' into enhance/AG-51049

commit f0575d22db41268aca5ef988f70d307b44abfde6
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Thu Apr 9 23:39:39 2026 +0300

    refactoring

commit 8e38d07df4f39a580ec9145e0fe27353dd7ed979
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Thu Apr 9 23:09:19 2026 +0300

    refactoring

commit 6fa6386bfab3bb6c8a98d08e1245876ac2f8d3cf
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Tue Apr 7 19:43:32 2026 +0300

    test fixme

commit bec24527f692ac57a00eb97ee166648fd5155d2f
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Tue Apr 7 19:16:05 2026 +0300

    refactoring

commit 2fb2126bbba9e9dd2c9cab70cc775a360d6688f7
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Tue Apr 7 18:59:23 2026 +0300

    add rule for class modificators and hyphen removing

commit 752103035bc6474aefbc059521627206044cb85c
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Tue Apr 7 18:01:06 2026 +0300

    remove FIXME

commit 3ab543db8dda148634793e21a88cbe47d9ca899c
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Tue Apr 7 16:04:08 2026 +0300

    add exit command

commit c3165b67d2bdb34e3fbe4db0e32d6e6257ed7c94
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Tue Apr 7 15:39:00 2026 +0300

    test fixme

commit f9df03ee6c443b8398313a4cddea0fcfc3ebbe11
Author: Alexandr Zaitsev <a.zaitsev@adguard.com>
Date:   Tue Apr 7 14:59:47 2026 +0300

    AG-51049 add FIXME check to build plan

diff --git a/bamboo-specs/tests.yaml b/bamboo-specs/tests.yaml
--- a/bamboo-specs/tests.yaml
+++ b/bamboo-specs/tests.yaml
@@ -44,6 +44,15 @@ Test:
             pnpm lint
             pnpm test:ci
 
+            # Block FIXME comments from reaching the master branch.
+            if [ "${bamboo.repository.pr.targetBranch}" = "master" ] \
+              || [ "${bamboo.planRepository.branchName}" = "master" ]; then
+              if grep -rn 'FIXME' --include='*.ts' --include='*.tsx' --include='*.js' --include='*.jsx' src/ tasks/; then
+                echo "ERROR: FIXME comments found. Remove them before merging to master."
+                exit 1
+              fi
+            fi
+
             # build with test API endpoints:
             # chrome.zip, edge.zip, opera.zip, firefox.zip
             STAGE_ENV=test \
